create table products (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description  VARCHAR(50) NOT NULL,
	price  VARCHAR(50) NOT NULL,
	delievered  VARCHAR(50) NOT NULL,
	not_delievered  VARCHAR(50)
);

insert into products (id, name, description , price , delievered , not_delievered ) values (1, 'Dodge', 'Ram Van 3500', '€2844325,69', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (2, 'Lexus', 'ES', '€9616554,73', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (3, 'Chevrolet', 'Silverado 1500', '€7260389,52', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (4, 'Buick', 'Century', '€1965687,91', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (5, 'Infiniti', 'QX56', '€9854826,41', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (6, 'Ford', 'E-Series', '€4824889,89', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (7, 'Honda', 'CR-V', '€4900310,04', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (8, 'Mazda', '929', '€9924742,91', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (9, 'Dodge', 'Sprinter', '€4205612,43', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (10, 'Ford', 'Aerostar', '€2534126,88', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (11, 'Mitsubishi', 'Eclipse', '€2902613,33', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (12, 'Mercury', 'Tracer', '€5419549,32', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (13, 'Geo', 'Metro', '€8294506,65', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (14, 'Subaru', 'Legacy', '€486441,60', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (15, 'BMW', 'Z4', '€2392223,35', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (16, 'Pontiac', 'Sunbird', '€7193643,07', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (17, 'Hummer', 'H1', '€6770737,38', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (18, 'Suzuki', 'Swift', '€8019513,16', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (19, 'Mercury', 'Villager', '€6752842,80', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (20, 'Buick', 'Riviera', '€1192004,86', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (21, 'Daewoo', 'Leganza', '€9228537,12', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (22, 'Dodge', 'Ram Van 3500', '€1182373,51', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (23, 'BMW', 'Z3', '€5635860,62', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (24, 'Cadillac', 'Fleetwood', '€1038240,10', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (25, 'Subaru', 'Alcyone SVX', '€7934365,98', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (26, 'Chevrolet', 'HHR', '€5250914,52', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (27, 'Chevrolet', 'Cavalier', '€9279151,72', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (28, 'Chevrolet', 'Monte Carlo', '€6546130,91', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (29, 'GMC', 'Sierra 2500', '€6941429,61', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (30, 'GMC', 'Sierra 2500', '€3617946,82', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (31, 'Dodge', 'Journey', '€295272,55', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (32, 'Land Rover', 'Freelander', '€5096918,36', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (33, 'Kia', 'Rio', '€2806226,61', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (34, 'BMW', 'M3', '€9525735,00', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (35, 'Toyota', 'Sienna', '€3388286,11', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (36, 'GMC', 'Safari', '€2640863,40', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (37, 'Volkswagen', 'GTI', '€2906911,05', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (38, 'GMC', 'Savana 2500', '€144654,47', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (39, 'Lincoln', 'Town Car', '€6414790,99', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (40, 'GMC', 'Yukon XL 2500', '€7318803,00', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (41, 'Ford', 'F350', '€9108876,17', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (42, 'Oldsmobile', '98', '€7400372,53', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (43, 'Honda', 'Accord', '€1213777,42', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (44, 'Buick', 'Electra', '€8465780,32', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (45, 'Mercedes-Benz', 'CLK-Class', '€7607340,76', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (46, 'Cadillac', 'Escalade EXT', '€6966594,77', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (47, 'Audi', '200', '€9029835,60', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (48, 'Chevrolet', 'Corvette', '€3020388,13', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (49, 'Bentley', 'Continental GTC', '€4552176,71', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (50, 'Cadillac', 'SRX', '€5493270,06', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (51, 'Mitsubishi', 'Mirage', '€4165934,66', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (52, 'Chevrolet', 'TrailBlazer', '€1543003,34', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (53, 'Pontiac', 'Aztek', '€2530715,05', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (54, 'Land Rover', 'Discovery', '€6218818,30', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (55, 'Lotus', 'Esprit Turbo', '€7449053,81', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (56, 'Ford', 'Bronco', '€6151479,03', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (57, 'Chevrolet', 'Avalanche', '€9469483,27', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (58, 'Kia', 'Optima', '€2489812,13', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (59, 'Chevrolet', 'Corvette', '€8917136,30', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (60, 'Lincoln', 'Mark LT', '€2217646,67', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (61, 'Volvo', 'S80', '€3687199,81', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (62, 'Chevrolet', 'Suburban 2500', '€7057254,55', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (63, 'Porsche', '911', '€116328,35', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (64, 'Buick', 'Coachbuilder', '€7966024,31', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (65, 'Hummer', 'H3', '€7579415,69', 'yes', '');
insert into products (id, name, description , price , delievered , not_delievered ) values (66, 'Cadillac', 'XLR', '€5518733,96', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (67, 'Nissan', 'Versa', '€7915548,38', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (68, 'Isuzu', 'Ascender', '€1920604,38', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (69, 'Cadillac', 'DeVille', '€8112760,53', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (70, 'Subaru', 'Brat', '€8830105,87', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (71, 'Volvo', '240', '€6340914,68', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (72, 'GMC', 'Sierra 1500', '€8159741,68', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (73, 'Plymouth', 'Colt Vista', '€1391343,93', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (74, 'Dodge', 'Dakota Club', '€6099618,98', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (75, 'Ford', 'Ranger', '€1847099,63', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (76, 'Ford', 'Mustang', '€5446433,07', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (77, 'Honda', 'Odyssey', '€9184592,52', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (78, 'Nissan', 'Maxima', '€2512780,76', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (79, 'BMW', '5 Series', '€3180417,12', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (80, 'Saab', '900', '€5312767,16', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (81, 'Oldsmobile', 'Silhouette', '€9180705,08', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (82, 'Volkswagen', 'Fox', '€7861044,60', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (83, 'Studebaker', 'Avanti', '€8438209,18', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (84, 'Chevrolet', 'G-Series G20', '€3523178,88', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (85, 'Ford', 'Bronco II', '€9885019,18', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (86, 'Honda', 'Ridgeline', '€6346800,88', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (87, 'MINI', 'Cooper Countryman', '€9515357,55', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (88, 'Mercedes-Benz', 'E-Class', '€694816,28', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (89, 'Toyota', 'RAV4', '€1719008,54', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (90, 'Chevrolet', 'Corsica', '€1872175,19', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (91, 'Ford', 'Flex', '€220415,07', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (92, 'Chevrolet', 'Suburban 1500', '€5739882,01', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (93, 'Chevrolet', 'Avalanche 1500', '€5447364,79', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (94, 'Dodge', 'Intrepid', '€2863057,23', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (95, 'Chevrolet', 'Express 1500', '€8315327,06', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (96, 'Mazda', 'Protege', '€3526769,00', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (97, 'Mitsubishi', 'Eclipse', '€8775091,17', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (98, 'Porsche', 'Panamera', '€8671055,59', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (99, 'Acura', 'Integra', '€185881,91', '', 'no');
insert into products (id, name, description , price , delievered , not_delievered ) values (100, 'Cadillac', 'XLR-V', '€9609537,72', '', 'no');
